### ISSUE TITLE
no module django_gamification

### ISSUE THREAD

**Issue by IT-special** [mattjegan/django-gamification-example-app#5]
(django-gamification-example-app) edugineer@edugineer-system:~/projects/django-gamification-example-app$ python3 manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f3f7706fea0>
Traceback (most recent call last):
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/edugineer/.local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_gamification'

**Comment by mattjegan** [comment]
I'll need some more information to help you, could you please provide the output for `pip list` and the content of `INSTALLED_APPS` in your settings.py

**Comment by mattjegan** [comment]
It looks like you may not have installed the requirements. Could you please provide the output of `pip list`.

**Comment by IT-special** [comment]
~/projects/django-gamification-example-app/djangogamificationexample$ pip
list
Package                Version
---------------------- -------------------
amqp                   2.4.1
appdirs                1.4.3
APScheduler            3.6.0
apturl                 0.5.2
arrow                  0.13.1
asn1crypto             0.24.0
billiard               3.6.0.0
blessed                1.15.0
Brlapi                 0.6.6
celery                 4.3.0
certifi                2018.11.29
chardet                3.0.4
Click                  7.0
command-not-found      0.3
coreapi                2.3.3
coreapi-cli            1.0.9
coreschema             0.0.4
cryptography           2.1.4
cupshelpers            1.0
defer                  1.0.6
defusedxml             0.5.0
distlib                0.3.0
distro-info            0.18ubuntu0.18.04.1
dj-database-url        0.5.0
Django                 2.1.7
django-bootstrap4      0.0.7
django-celery-beat     1.4.0
django-celery-results  1.0.4
django-colorful        1.3
django-compat          1.0.15
django-extensions      2.1.6
django-filter          2.2.0
django-heroku          0.3.1
django-picklefield     2.0
django-redis           4.10.0
django-timezone-field  3.0
django-tinymce         2.8.0
djangorestframework    3.9.2
filelock               3.0.12
graphviz               0.10.1
gunicorn               19.9.0
httplib2               0.9.2
idna                   2.8
importlib-metadata     1.6.0
importlib-resources    1.4.0
itypes                 1.1.0
Jinja2                 2.10
jsonhyperschema-codec  1.0.3
keyring                10.6.0
keyrings.alt           3.0
kombu                  4.5.0
language-selector      0.1
launchpadlib           1.10.6
lazr.restfulclient     0.13.5
lazr.uri               1.0.3
louis                  3.5.0
macaroonbakery         1.1.3
Mako                   1.0.7
MarkupSafe             1.1.1
netifaces              0.10.4
oauth                  1.0.1
oauthlib               3.0.1
olefile                0.45.1
pexpect                4.2.1
Pillow                 5.4.1
pip                    20.0.2
pipenv                 2018.11.26
protobuf               3.0.0
psycopg2               2.7.7
psycopg2-binary        2.7.7
pycairo                1.16.2
pycrypto               2.6.1
pycups                 1.9.73
pydot                  1.4.1
pydotplus              2.0.2
pygobject              3.26.1
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.1.2
pyparsing              2.4.0
pyRFC3339              1.0
python-apt             1.6.5+ubuntu0.2
python-crontab         2.3.6
python-dateutil        2.8.0
python-debian          0.1.32
python3-openid         3.1.0
pytz                   2018.9
pyxdg                  0.25
PyYAML                 3.12
redis                  3.2.1
reportlab              3.4.0
requests               2.21.0
requests-oauthlib      1.2.0
requests-unixsocket    0.1.5
SecretStorage          2.3.1
setuptools             46.1.3
simplejson             3.13.2
six                    1.12.0
social-auth-app-django 3.1.0
social-auth-core       3.1.0
system-service         0.3
systemd-python         234
tzlocal                1.5.1
ubuntu-drivers-common  0.0.0
ufw                    0.36
unattended-upgrades    0.1
uritemplate            3.0.0
urllib3                1.24.1
usb-creator            0.3.3
vine                   1.3.0
virtualenv             20.0.18
virtualenv-clone       0.5.4
wadllib                1.3.2
wcwidth                0.1.7
wheel                  0.30.0
whitenoise             4.1.2
xkit                   0.0.0
zipp                   3.1.0
zope.interface         4.3.2

**Comment by IT-special** [comment]
in settings.py file

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_gamification',
    'django_extensions',
    'app',
]

**Comment by IT-special** [comment]
i started learn about gamification, and find your project but i can not to
run, please help me

**Comment by mattjegan** [comment]
No worries, you're missing the django-gamification package. You need to run:
```
pip install django-gamification
python manage.py migrate
python manage.py create-examples
python manage.py runserver
```

**Comment by IT-special** [comment]
thank you very much, Matthew, the project is working now

Dear Matthew, I am a student at the Faculty of Computer Science, I have now
an LMS project written in Python Django and our company where I do practice
want to integrate gamification
could you please give some source link for understanding more about
gamification or wHAT DO YOU ADVISE FOR WORK WITH GAMIFICATION, WITH WHAT TO
START ME WITH?
